development:
  adapter: postgresql
  encoding: unicode
  database: gwc_development
  pool: 5
  username: rbobbins
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: gwc_test
  pool: 5
  username: rbobbins
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: gwc_production
  pool: 5
  username: username
  password:
